openapi: 3.0.3
info:
  title: Kazyon Services for iVend
  description: |-
    This API's will be used by iVend to integrate Kazyon services (there is an API that will get the list of services) and will be cached for 24 hours and will be retrieved daily to get any new updates on the list of services.
  
  contact:
    email: mohamed.nasr@kazyon.com
  version: 1.0.01
servers:
  - url: will be available soon...
tags:
  - name: service
    description: Everything about getting available services, validating user eligibility, discount conditions, vouchers details ... etc 

    
    
paths:
  /service:
    get:
      tags:
        - service
      summary: get all the offered services and all required input parameter to be sent to validation service
      description: This service will be called once daily by iVend to cache all the required information
      operationId: getServicesInfo
      parameters:
        - $ref: '#/components/parameters/storeCode'
        - $ref: '#/components/parameters/storePassword'
      
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/servicesInfo'
                example:
                  - serviceProvider: orange
                    attributes:
                    - name: mobileNumber
                      type: string
                      minLength: 11
                      maxLength: 11
                      shownInUI: true
                      regexValidation: '^01\d{9}$'
                      
                    - name: code
                      type: string
                      minLength: 4
                      maxLength: 20
                      shownInUI: true
                      
                    - name: otp
                      type: number
                      minLength: 6
                      maxLength: 8
                      shownInUI: true
                    
                    - name: voucherType
                      type: string
                      minLength: 5
                      maxLength: 15
                      shownInUI: false
                      
                  - serviceProvider: vodafone
                    attributes:
                      - name: mobileNumber
                        type: string
                        minLength: 11
                        maxLength: 11
                        shownInUI: true
                        validation: '^01\d{9}$'
                        
                      - name: code
                        type: string
                        minLength: 4
                        maxLength: 20
                        shownInUI: true
                        
                      - name: voucherType
                        type: string
                        minLength: 5
                        maxLength: 15
                        shownInUI: false
                        
                        
                  
                  
        '401':
          $ref: '#/components/responses/UnauthorizedError'
     
  /service/eligibilty:
    post:
      tags:
       - service
      summary: check wether the user is eligible to use an offer or validate a coupon code
      description: This service will be called with every transaction including voucher or coupon to validate the user's eligabilty to reedem the code
      operationId: getUserEligibility
      parameters:
        - $ref: '#/components/parameters/storeCode'
        - $ref: '#/components/parameters/storePassword'
      
      requestBody:
        description: Send all required parameters as input body that you are already aware of from the [GET] service
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/eligibilityRequest'
              
              
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: 
                  $ref: '#/components/schemas/eligibiltyResponse'
                  
        '401':
          $ref: '#/components/responses/UnauthorizedError'
         
            
          
  
components: 
  parameters:
    storeCode:
      name: storeCode
      in: header
      description: storeCode
      required: true
      schema:
        type: string
    storePassword:
      name: storePassword
      in: header
      description: store password, will be provided for each store
      required: true
      schema:
        type: string
  responses:
      UnauthorizedError:
        description: Authentication information is missing or invalid
       
  schemas:
    eligibilityRequest:
      type: object
      properties:
      
        serviceProvider:
          type: string
          enum:
              - vodafone
              - orange
              - etisalat
        mobileNumber:
          type: string
          example: "01234567899"
        code:
          type: string
          example: "KZ123"
        otp:
          type: string
          example: "123456"
        codeType:
          type: string 
          description: it can be "voucher" or "coupon"
          enum:
            - voucher
            - coupon
        
    eligibiltyResponse:
      type: object
      properties:
        isValid:
          type: boolean
          description: it's a flag to tell if the user is eligable to reedem the code or not
          example: true
        voucherType:
          type: string
          description:  it describes the meaning of the value contained in discountValue it can be one of those values "voucherValue", "discountPercentage", "bounsBuyGroup" or "couponValue"
          example: "voucherValue || discountPercentage || couponValue || bounsBuyGroup"
        maxDiscountAmount:
          type: number
          description: highest ammount of money that can be deducted from the transtaction ex. dicount 15% up to 100 pounds 
          example: 70
        minimumReceiptAmount:
          type: number
          description: the minimum ammount of money of the receipt for the discount to be eligable
          example: 250
        discountValue:
          type: string
          description: can hold one of those 4 values types accornding to the type mentioned in voucherType
          example: "10 || 0.4 || 0.65 || bonusBuyGroup1"
        loyaltyEligibilityPercent:
          type: number
          example: 0.55 || 0.65 || 0.80
          description: should be a fraction value between 0.0 to 1.0 
    servicesInfo:
        type: object
        properties:
          serviceProvider: 
            type: string
            enum:
                  - vodafone
                  - orange
                  - etisalat
            example: orange
          attributes:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                voucherType:
                  type: string
                minLength:
                  type: number
                maxLength:
                  type: number
                shownInUI:
                  type: boolean
                regexValidation:
                  type: string
        
   