openapi: 3.0.3
info:
  title: Kazyon Services for iVend
  description: |-
    This project is consist of 2 API's, and they will be used by iVend to integrate with Kazyon (Coupon and Voucher) Services, one of them is concerned to get all the needed information about the available service and the other one is concernded to validate how on validating the user eligibility for a specific Coupon or Voucher. 
    <br> <h2> The first API (Get Service) </h2> will be called on each start up for any POS machine or every 24 hours to enable bandwith and caching capabilities. This will save a lot of calls and bandwith consumtion.
    <br> <h2> The second API (Post eligibility) </h2> will be called to validate the user eligibility for a coupon or a voucher, and it will get the rquired coupon or voucher information, ex: percentage of discount, maximum discount amount, and minimum receipt value ... etc.  
    <br> <h2> User Defined Table(UDT) </h2> stored in IVend database and contains all data needed about the transactions on which a discound has been applied. the contient of the table is receiptNumber(generated by IVend during the transaction process), transactionId(generated by IVend during the transaction process), eligibilityTransactionId(provided by kazyon in the check eligibility response), serviceId(provided by kazyon in get all services response), appliedDiscountAmmount(calculated by IVend during rhe transaction process)
  

  contact:
    email: mohamed.nasr@kazyon.com
  version: 1.0.01
servers:
  - url: will be available soon...
tags:
  - name: service
    description: Everything about getting available services, validating user eligibility, discount conditions, vouchers details and so on.



paths:
  /service:
    get:
      tags:
        - service
      summary: get all the offered services and all required input parameter to be sent to validation service
      description: This service will be called once daily by iVend to cache all the required information
      operationId: getServicesInfo
      parameters:
        - $ref: '#/components/parameters/storeCode'
        - $ref: '#/components/parameters/storePassword'

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/servicesInfo'
                example:
                  - serviceProvider: orange
                    coupons:
                      - serviceId: orangeCoupon200
                        displayName: Orange coupon 200
                        icon: <icon_path>
                        attributes:
                          - name: mobileNumber
                            type: string
                            minLength: 11
                            maxLength: 11
                            shownInUI: true
                            regexValidation: '^01\d{9}$'
                            displayName: رقم المحمول

                          - name: code
                            type: string
                            minLength: 4
                            maxLength: 20
                            shownInUI: true
                            displayName: الكود


                          - name: otp
                            type: number
                            minLength: 6
                            maxLength: 8
                            shownInUI: true
                            displayName: رمز التحقق
                      - serviceId: orangeCoupon5P
                        displayName: Orange coupon 5%
                        icon: <icon_path>
                        attributes:
                          - name: mobileNumber
                            type: string
                            minLength: 11
                            maxLength: 11
                            shownInUI: true
                            regexValidation: '^01\d{9}$'
                            displayName: رقم المحمول

                          - name: code
                            type: string
                            minLength: 4
                            maxLength: 20
                            shownInUI: true
                            displayName: الكود

                    vouchers:
                      - serviceId: orangeVoucher100
                        displayName: Orange voucher 100
                        icon: <icon_path>
                        attributes:
                          - name: mobileNumber
                            type: string
                            minLength: 11
                            maxLength: 11
                            shownInUI: true
                            regexValidation: '^01\d{9}$'
                            displayName: رقم المحمول

                          - name: code
                            type: string
                            minLength: 4
                            maxLength: 20
                            shownInUI: true
                            displayName: الكود


                          - name: otp
                            type: number
                            minLength: 6
                            maxLength: 8
                            shownInUI: true
                            displayName: رمز التحقق

                  - serviceProvider: vodafone
                    coupons:
                      - serviceId: vodafoneCoupon50
                        displayName: Vodafone coupon 50
                        icon: <icon_path>
                        attributes:
                          - name: mobileNumber
                            type: string
                            minLength: 11
                            maxLength: 11
                            shownInUI: true
                            regexValidation: '^01\d{9}$'
                            displayName: رقم المحمول

                          - name: code
                            type: string
                            minLength: 4
                            maxLength: 20
                            shownInUI: true
                            displayName: الكود

                          - name: otp
                            type: number
                            minLength: 6
                            maxLength: 8
                            shownInUI: true
                            displayName: رمز التحقق

                    vouchers:
                      -

        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /service/eligibilty:
    post:
      tags:
        - service
      summary: check wether the user is eligible to use an offer or validate a coupon code
      description: This service will be called with every transaction including one or more vouchers or coupons to validate the user's eligabilty to reedem these codes, the api takes an array of objects each object contains all the required data about one voucher or coupon in the example we show a request containing one coupon, in case of multible coupons or vouchers the array will contain multible object each containing the required attributes for this coupon or voucher so the objects don't have to be similar. The response will be an array containing same number of objects as the request. the objects in the response will all have the same attributes as shown in example but different values.
      operationId: checkUserEligibility
      parameters:
        - $ref: '#/components/parameters/storeCode'
        - $ref: '#/components/parameters/storePassword'

      requestBody:
        description: Send all required parameters as input body that you are already aware of from the [GET] service
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/eligibilityRequest'


      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/eligibiltyResponse'

        '401':
          $ref: '#/components/responses/UnauthorizedError'




components:
  parameters:
    storeCode:
      name: storeCode
      in: header
      description: storeCode
      required: true
      schema:
        type: string
    storePassword:
      name: storePassword
      in: header
      description: store password, will be provided for each store
      required: true
      schema:
        type: string
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid

  schemas:
    eligibilityRequest:
      type: object
      properties:
        serviceId:
          type: string
          description: contains the unique identifier for the chosen service
          example: vodafoneCoupon50
        mobileNumber:
          type: string
          example: "01234567899"
        code:
          type: string
          example: "KZ123"
        otp:
          type: string
          example: "123456"


    eligibiltyResponse:
      type: object
      properties:
        serviceId:
          type: string
          description: contains the unique identifier for the chosen service
          example: vodafoneCoupon50
        status:
          type: string
          enum:
            - Eligible
            - AlreadyUsed
            - NotEligible
          example: "NotEligible  || AlreadyUsed ||  Eligible"
          description: it's a enum to have status of check eligiblity  it can be (Eligible ->  user eligible to use this code), (alreadyUsed ->  code used before.) or (notEligible ->  user  not eligible to use this code.)

        statusMessage:
          type: string
          example: " يمكنك استخدام هذا الكود  ||   تم استخدام الكود من قبل  ||    هذا الكود غير صالح للاستخدام "
        couponOrVoucherKind:
          type: string
          description:  it describes the meaning of the value contained in discountValue it can be one of those values "voucherValue", "discountPercentage", "bounsBuyGroup", "voucherPercentage" or "couponValue"
          example: "voucherValue || discountPercentage || couponValue || bounsBuyGroup || voucherPercentage"
        maxDiscountAmount:
          type: number
          description: highest ammount of money that can be deducted from the transtaction ex. dicount 15% up to 100 pounds
          example: 70
        minimumReceiptAmount:
          type: number
          description: the minimum ammount of money of the receipt for the discount to be eligable
          example: 250
        discountValue:
          type: string
          description: can hold one of those 4 values types accornding to the type mentioned in couponOrVoucherKind
          example: "10 || 0.4 || 0.65 || bonusBuyGroup1 || 0.45"
        loyaltyEligibilityPercent:
          type: number
          example: 0.55 || 0.65 || 0.80
          description: should be a fraction value between 0.0 to 1.0
        eligibilityTransactionId:
          type: string
          example: eligibility0012345
          description: unique identifier for each transaction, should be stored in User-Defined Table (UDT).


    servicesInfo:
      type: object
      properties:
        serviceProvider:
          type: string
          enum:
            - vodafone
            - orange
            - etisalat
            - meeza
        coupons:
          type: array
          description: list of all coupons for this service provider
          items:
            type: object
            properties:
              serviceId:
                type: string
                description: unique identifier for each service
                example: Orange
              displayName:
                type: string
                description: name to be displayed in UI
                example: Orange
              icon:
                type: string
                description: icon path for the service
              attributes:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    minLength:
                      type: number
                    maxLength:
                      type: number
                    shownInUI:
                      type: boolean
                    regexValidation:
                      type: string
                    displayName:
                      type: string
        vouchers:
          type: array
          description: list of all vouchers for this service provider
          items:
            type: object
            properties:
              serviceId:
                type: string
                description: unique identifier for each service
                example: Orange
              displayName:
                type: string
                description: name to be displayed in UI
                example: Orange
              icon:
                type: string
                description: icon path for the service
              attributes:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    minLength:
                      type: number
                    maxLength:
                      type: number
                    shownInUI:
                      type: boolean
                    regexValidation:
                      type: string
                    displayName:
                      type: string
