openapi: 3.0.3
info:
  title: Kazyon Services for iVend
  description: |-
    This project is consist of 2 API's, and they will be used by iVend to integrate with Kazyon (Coupon and Voucher) Services, one of them is concerned to get all the needed information about the available service and the other one is concernded to validate how on validating the user eligibility for a specific Coupon or Voucher. 
    <br> <h2> The first API (Get Service) </h2> will be called on each start up for any POS machine or every 24 hours to enable bandwith and caching capabilities. This will save a lot of calls and bandwith consumtion.
    <br> <h2> The second API (Post eligibility) </h2> will be called to validate the user eligibility for a coupon or a voucher, and it will get the rquired coupon or voucher information, ex: percentage of discount, maximum discount amount, and minimum receipt value ... etc.  
  
  contact:
    email: mohamed.nasr@kazyon.com
  version: 1.0.01
servers:
  - url: will be available soon...
tags:
  - name: service
    description: Everything about getting available services, validating user eligibility, discount conditions, vouchers details and so on.

    
    
paths:
  /service:
    get:
      tags:
        - service
      summary: get all the offered services and all required input parameter to be sent to validation service
      description: This service will be called once daily by iVend to cache all the required information
      operationId: getServicesInfo
      parameters:
        - $ref: '#/components/parameters/storeCode'
        - $ref: '#/components/parameters/storePassword'
      
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/servicesInfo'
                example:
                  - serviceProvider: orange
                    codeType: coupon
                    displayName: Orange coupon
                    icon: <icon_path>
                    attributes:
                    - name: mobileNumber
                      type: string
                      minLength: 11
                      maxLength: 11
                      shownInUI: true
                      regexValidation: '^01\d{9}$'
                      displayName: رقم المحمول
                      
                    - name: code
                      type: string
                      minLength: 4
                      maxLength: 20
                      shownInUI: true
                      displayName: الكود
                      
                    - name: otp
                      type: number
                      minLength: 6
                      maxLength: 8
                      shownInUI: true
                      displayName: رمز التحقق
                    
                  
                      
                  - serviceProvider: orange
                    codeType: voucher
                    displayName: Orange Voucher
                    icon: <icon_path>
                    attributes:
                    - name: mobileNumber
                      type: string
                      minLength: 11
                      maxLength: 11
                      shownInUI: true
                      regexValidation: '^01\d{9}$'
                      displayName: رقم المحمول
                      
                    - name: code
                      type: string
                      minLength: 4
                      maxLength: 20
                      shownInUI: true
                      displayName: الكود

                      
                    - name: otp
                      type: number
                      minLength: 6
                      maxLength: 8
                      shownInUI: true
                      displayName: رمز التحقق
                    
                      
                  - serviceProvider: vodafone
                    codeType: voucher
                    displayName: Vodafone Voucher
                    icon: <icon_path>
                    attributes:
                      - name: mobileNumber
                        type: string
                        minLength: 11
                        maxLength: 11
                        shownInUI: true
                        regexValidation: '^01\d{9}$'
                        displayName: رقم المحمول
                        
                      - name: code
                        type: string
                        minLength: 4
                        maxLength: 20
                        displayName: الكود

                  
                  
        '401':
          $ref: '#/components/responses/UnauthorizedError'
     
  /service/eligibilty:
    post:
      tags:
       - service
      summary: check wether the user is eligible to use an offer or validate a coupon code
      description: This service will be called with every transaction including voucher or coupon to validate the user's eligabilty to reedem the code
      operationId: checkUserEligibility
      parameters:
        - $ref: '#/components/parameters/storeCode'
        - $ref: '#/components/parameters/storePassword'
      
      requestBody:
        description: Send all required parameters as input body that you are already aware of from the [GET] service
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/eligibilityRequest'
              
              
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: 
                  $ref: '#/components/schemas/eligibiltyResponse'
                  
        '401':
          $ref: '#/components/responses/UnauthorizedError'
         
            
          
  
components: 
  parameters:
    storeCode:
      name: storeCode
      in: header
      description: storeCode
      required: true
      schema:
        type: string
    storePassword:
      name: storePassword
      in: header
      description: store password, will be provided for each store
      required: true
      schema:
        type: string
  responses:
      UnauthorizedError:
        description: Authentication information is missing or invalid
       
  schemas:
    eligibilityRequest:
      type: object
      properties:
        serviceProvider:
          type: string
          enum:
              - vodafone
              - orange
              - etisalat
              - meeza
        codeType:
          type: string 
          description: it can be "voucher" or "coupon"
          enum:
            - voucher
            - coupon
        mobileNumber:
          type: string
          example: "01234567899"
        code:
          type: string
          example: "KZ123"
        otp:
          type: string
          example: "123456"
        
        
    eligibiltyResponse:
      type: object
      properties:
        status:
           type: string
           enum:
                  - availableToUse
                  - alreadyUsed
                  - notEligible
           example: "notEligible  || alreadyUsed ||  availableToUse"
           description: it's a enum to have status of check eligiblity  it can be (availableToUse -> user can use discount), (alreadyUsed -> this voucher or coupon already used before) or (notEligible -> voucher or coupon not valid)
        
        statusMessage:
          type: string
          example: " يمكنك استخدام هذا الكود  ||   تم استخدام الكود من قبل  ||    هذا الكود غير صالح للاستخدام "
        couponOrVoucherKind:
          type: string
          description:  it describes the meaning of the value contained in discountValue it can be one of those values "voucherValue", "discountPercentage", "bounsBuyGroup" or "couponValue"
          example: "voucherValue || discountPercentage || couponValue || bounsBuyGroup"
        maxDiscountAmount:
          type: number
          description: highest ammount of money that can be deducted from the transtaction ex. dicount 15% up to 100 pounds 
          example: 70
        minimumReceiptAmount:
          type: number
          description: the minimum ammount of money of the receipt for the discount to be eligable
          example: 250
        discountValue:
          type: string
          description: can hold one of those 4 values types accornding to the type mentioned in couponOrVoucherKind
          example: "10 || 0.4 || 0.65 || bonusBuyGroup1"
        loyaltyEligibilityPercent:
          type: number
          example: 0.55 || 0.65 || 0.80
          description: should be a fraction value between 0.0 to 1.0 
    
    servicesInfo:
        type: object
        properties:
          serviceProvider: 
            type: string
            enum:
                  - vodafone
                  - orange
                  - etisalat
                  - meeza
            example: orange
          codeType:
            type: string 
            description: it can be "voucher" or "coupon"
            enum:
              - voucher
              - coupon
            example: coupon
          displayName:
            type: string 
            description: name to be displayed in UI
            example: Orange
          icon:
            type: string 
            description: icon path for the service
          attributes:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                minLength:
                  type: number
                maxLength:
                  type: number
                shownInUI:
                  type: boolean
                regexValidation:
                  type: string
                displayName:
                  type: string
        
   
